### ISSUE TITLE
fail install app-emulation/genymotion-9999::open-overlay

### ISSUE THREAD

**Issue by nyim** [pantera31752/open-overlay#10]
cat /var/tmp/portage/app-emulation/genymotion-9999/temp/build.log
 * Package:    app-emulation/genymotion-9999
 * Repository: open-overlay
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux qt4 qt5 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking genymotion-9999.tar.gz to /var/tmp/portage/app-emulation/genymotion-9999/work
>>> Source unpacked in /var/tmp/portage/app-emulation/genymotion-9999/work
>>> Preparing source in /var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999 ...
>>> Source compiled.
>>> Test phase [not enabled]: app-emulation/genymotion-9999

>>> Install genymotion-9999 into /var/tmp/portage/app-emulation/genymotion-9999/image/ category app-emulation
chmod: cannot access ‘{/opt/genymotion}/genymotion/genymotion/gmtool’: No such file or directory
 * ERROR: app-emulation/genymotion-9999::open-overlay failed (install phase):
 *   fperms failed
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/genymotion-9999::open-overlay'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/genymotion-9999::open-overlay'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/genymotion-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/genymotion-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999'
 * S: '/var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999'

**Comment by pantera31752** [comment]
I want see log build

**Comment by nyim** [comment]
1   * Package:    app-emulation/genymotion-9999
     2   * Repository: open-overlay
     3   * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux qt4 qt5 userland_GNU
     4   * FEATURES:   preserve-libs sandbox userpriv usersandbox
     5  >>> Unpacking source...
     6  >>> Unpacking genymotion-9999.tar.gz to /var/tmp/portage/app-emulation/genymotion-9999/work
     7  >>> Source unpacked in /var/tmp/portage/app-emulation/genymotion-9999/work
     8  >>> Preparing source in /var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999 ...
     9  >>> Source prepared.
    10  >>> Configuring source in /var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999 ...
    11  >>> Source configured.
    12  >>> Compiling source in /var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999 ...
    13  >>> Source compiled.
    14  >>> Test phase [not enabled]: app-emulation/genymotion-9999
    15
    16  >>> Install genymotion-9999 into /var/tmp/portage/app-emulation/genymotion-9999/image/ category app-emulation
    17  chmod: cannot access ‘{/opt/genymotion}/genymotion/gmtool’: No such file or directory
    18   * ERROR: app-emulation/genymotion-9999::open-overlay failed (install phase):
    19   *   fperms failed
    20   * 
    21   * If you need support, post the output of `emerge --info '=app-emulation/genymotion-9999::open-overlay'`,
    22   * the complete build log and the output of `emerge -pqv '=app-emulation/genymotion-9999::open-overlay'`.
    23   * The complete build log is located at '/var/tmp/portage/app-emulation/genymotion-9999/temp/build.log'.
    24   * The ebuild environment file is located at '/var/tmp/portage/app-emulation/genymotion-9999/temp/environment'.
    25   * Working directory: '/var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999'
    26   * S: '/var/tmp/portage/app-emulation/genymotion-9999/work/genymotion-9999'


I am sorry, but I still can't install..

**Comment by pantera31752** [comment]
I'm sorry I'll make it right

**Comment by pantera31752** [comment]
All right.

**Comment by nyim** [comment]
It works. Thank you
