### ISSUE TITLE
Add support to epubs in app-text/atril

### ISSUE THREAD

**Issue by jorgicio** [pantera31752/open-overlay#12]
Hi! Thanks for your contribution with recent version of MATE. However, epub support in atril is disabled.
Please, at least, add the useflag "epub" and the line $(use_enable epub) in the ebuild.

Thanks.

**Comment by pantera31752** [comment]
Hi, I add later useflag epub

**Comment by pantera31752** [comment]
I added useflag, you can reemerge atril with epub

**Comment by pantera31752** [comment]
Thank you

**Comment by jorgicio** [comment]
You're welcome :D 
Also, I forgot one thing to mention: If use epub (as it uses gtk2), add net-libs/webkit-gtk:2 as a dependency.
Thanks again :D

**Comment by pantera31752** [comment]
I'm sorry, I just never used epub :D

**Comment by jorgicio** [comment]
I do on my mobile, but anyway... thanks again :D
