### ISSUE TITLE
dev-util/eclipse-jee-bin missing bin and config

### ISSUE THREAD

**Issue by HelLViS69** [pantera31752/open-overlay#18]
Hi,
I just tried to install eclipse-jee-bin but in the last steps emerge complains about missing files (there are, but with different names)

Here's the log:
>>> Emerging (1 of 1) dev-util/eclipse-jee-bin-4.5.1::open-overlay
>>> Failed to emerge dev-util/eclipse-jee-bin-4.5.1, Log file:
>>>  '/var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 2.46, 1.32, 0.87
 * Package:    dev-util/eclipse-jee-bin-4.5.1
 * Repository: open-overlay
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox

>>> Unpacking source...
>>> Unpacking eclipse-jee-bin-4.5.1-x86_64.tar.gz to /var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work
>>> Source unpacked in /var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work
>>> Preparing source in /var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work/eclipse ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work/eclipse ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work/eclipse ...
>>> Source compiled.
>>> Test phase [not enabled]: dev-util/eclipse-jee-bin-4.5.1

>>> Install eclipse-jee-bin-4.5.1 into /var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/image/ category dev-util
cp: cannot stat ‘/var/lib/layman/open-overlay/dev-util/eclipse-jee-bin/files/eclipserc-bin’: No such file or directory
 * ERROR: dev-util/eclipse-jee-bin-4.5.1::open-overlay failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  93:  Called src_install
 *   environment, line 2063:  Called die
 * The specific snippet of code:
 *       cp "${FILESDIR}"/eclipserc-bin "${T}" || die;
 * 
 * If you need support, post the output of `emerge --info '=dev-util/eclipse-jee-bin-4.5.1::open-overlay'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/eclipse-jee-bin-4.5.1::open-overlay'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work/eclipse'
 * S: '/var/tmp/portage/dev-util/eclipse-jee-bin-4.5.1/work/eclipse'

Let me know if you need more info
By the way, thanks for your work!

**Comment by pantera31752** [comment]
I'm sorry, I now fix, Thanks

**Comment by pantera31752** [comment]
All done. You can install. Thanks

**Comment by HelLViS69** [comment]
It works, thanks!

**Comment by HelLViS69** [comment]
Now it doesn't start, there's a " missing
Here's the patch:

--- eclipse-bin-4.5 2015-10-09 11:32:55.446074850 +0200
+++ eclipse-bin-4.5.new 2015-10-09 11:42:07.373079546 +0200
@@ -14,7 +14,7 @@
[ -f "/etc/eclipserc-bin-${SLOT}" ] && . "/etc/eclipserc-bin-${SLOT}"
[ -f "$HOME/gentoo/.eclipserc" ] && . "$HOME/gentoo/.eclipserc"

-ECLIPSE_HOME=${ECLIPSE_HOME:="/opt/eclipse-jee-bin-4.5}
+ECLIPSE_HOME=${ECLIPSE_HOME:="/opt/eclipse-jee-bin-${SLOT}"}
ECLIPSE_BIN="${ECLIPSE_HOME}/eclipse"

if [ ! -x "${ECLIPSE_BIN}" ] ; then

**Comment by pantera31752** [comment]
I'm sorry for this missing, I now fix

**Comment by pantera31752** [comment]
All right
