### ISSUE TITLE
mate-extra/caja-dropbox failed patch

### ISSUE THREAD

**Issue by jorgicio** [pantera31752/open-overlay#22]
Hi! Be careful at calling patches with versions in the ebuild.
This happens:

 * Package:    mate-extra/caja-dropbox-1.12.0
 * Repository: open-overlay
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found kernel object directory:
 *     /lib/modules/4.1.12-gentoo/build
 * Found sources for kernel version:
 *     4.1.12-gentoo
 * Checking for suitable kernel configuration options...
 [ ok ]
 * Fixing OMF Makefiles ...
 [ ok ]
 * Disabling deprecation warnings ...
 [ ok ]
 * Running elibtoolize in: caja-dropbox-1.12.0/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.4.2 patch ...
 *   Applying target-nm/2.4.2 patch ...

 * Cannot find $EPATCH_SOURCE!  Value for $EPATCH_SOURCE is:
 * 
 *   /var/lib/layman/open-overlay/mate-extra/caja-dropbox/files/caja-dropbox-1.12.0-system-rst2man.patch
 *   ( caja-dropbox-1.12.0-system-rst2man.patch )

 * ERROR: mate-extra/caja-dropbox-1.12.0::open-overlay failed (prepare phase):
 *   Cannot find $EPATCH_SOURCE!
 * 
 * Call stack:
 *     ebuild.sh, line   90:  Called src_prepare
 *   environment, line 5138:  Called epatch '/var/lib/layman/open-overlay/mate-extra/caja-dropbox/files/caja-dropbox-1.12.0-system-rst2man.patch'
 *   environment, line 2035:  Called die
 * The specific snippet of code:
 *                   die "Cannot find \$EPATCH_SOURCE!";
 * 
 * If you need support, post the output of `emerge --info '=mate-extra/caja-dropbox-1.12.0::open-overlay'`,
 * the complete build log and the output of `emerge -pqv '=mate-extra/caja-dropbox-1.12.0::open-overlay'`.
 * The complete build log is located at '/var/tmp/portage/mate-extra/caja-dropbox-1.12.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/mate-extra/caja-dropbox-1.12.0/temp/environment'.
 * Working directory: '/var/tmp/portage/mate-extra/caja-dropbox-1.12.0/work/caja-dropbox-1.12.0'
 * S: '/var/tmp/portage/mate-extra/caja-dropbox-1.12.0/work/caja-dropbox-1.12.0'

**Comment by pantera31752** [comment]
Hi, all right, you can emerge. thanks
