### ISSUE TITLE
net-libs/webkit-gtk-2.11.1 fails to build

### ISSUE THREAD

**Issue by rinaldus** [pantera31752/open-overlay#23]
Here's build.log.gz: https://yadi.sk/d/HHkbpoxDkHriB

**Comment by pantera31752** [comment]
Thanks for issue. I fix later

**Comment by pantera31752** [comment]
Try add "-ldl" flags in LDFLAGS and LIBS in your make.conf

**Comment by rinaldus** [comment]
Yes, it works. But is possible to fix this ebuild to have compile it without adding anything in make.conf?

**Comment by pantera31752** [comment]
Yes, I now fix. Thanks for issue

**Comment by pantera31752** [comment]
Try emerge now

**Comment by rinaldus** [comment]
I guess, you made mistake in
```
use x86 && append-ldflags "-|dl" 
```
| is not l letter
I could compile at home computer before your fix, but I can't compile on server now. Here's build.log: https://yadi.sk/i/hQXlCaV9kJLk8

**Comment by rinaldus** [comment]
Here's my pull request: https://github.com/pantera31752/open-overlay/pull/24

**Comment by pantera31752** [comment]
I'm sorry. Thanks
