### ISSUE TITLE
eclipse-cpp-4.4.1-r4 newbin error

### ISSUE THREAD

**Issue by DevPump** [pantera31752/open-overlay#5]
When I attempt to install eclipse-cpp-4.4.1-r4 from your overlay, I recieve this a newbin errror.

I have tried using other ebuild variables such as "${D}" and "${ROOT}", as well as a direct path with no success.

Build log:
>>>[32;01m * [39;49;00mPackage:    dev-util/eclipse-cpp-4.4.1-r4
>>>[32;01m * [39;49;00mRepository: open-overlay
>>>[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
>>>[32;01m * [39;49;00mFEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking eclipse-cpp-luna-SR2-linux-gtk-x86_64-4.4.1.tar.gz to /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work
>>> Source unpacked in /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work
>>> Preparing source in /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work/eclipse ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work/eclipse ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work/eclipse ...
>>> Source compiled.
>>> Test phase [not enabled]: dev-util/eclipse-cpp-4.4.1-r4

>>> Install eclipse-cpp-4.4.1-r4 into /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/image/ category dev-util
 [31;01m*[0m ERROR: dev-util/eclipse-cpp-4.4.1-r4::open-overlay failed (install phase):
 [31;01m*[0m   !!! newbin: /var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/temp/eclipse-cpp-9999 does not exist
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=dev-util/eclipse-cpp-4.4.1-r4::open-overlay'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=dev-util/eclipse-cpp-4.4.1-r4::open-overlay'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work/eclipse'
 [31;01m*[0m S: '/var/tmp/portage/dev-util/eclipse-cpp-4.4.1-r4/work/eclipse'

If any more information is needed, please let me know.

Thanks,
DevPump (Matt Fleming)

**Comment by pantera31752** [comment]
hi, I will fix later

**Comment by pantera31752** [comment]
I fixed ebuilds for eclipse-cpp. Thanks open-overlay by Alex
