### ISSUE TITLE
error building www-client/firefox-39.0_beta1

### ISSUE THREAD

**Issue by alcazoid** [pantera31752/open-overlay#9]
* Failed Patch: 6001_add_alpha_defines_in_ipc.patch !
 *  ( /var/tmp/portage/www-client/firefox-39.0_beta1/work/firefox/6001_add_alpha_defines_in_ipc.patch )
 * 
 * Include in your bugreport the contents of:
 * 
 *   /var/tmp/portage/www-client/firefox-39.0_beta1/temp/6001_add_alpha_defines_in_ipc.patch.out
 * ERROR: www-client/firefox-39.0_beta1::open-overlay failed (prepare phase):
 *   Failed Patch: 6001_add_alpha_defines_in_ipc.patch!
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 5076:  Called epatch '/var/tmp/portage/www-client/firefox-39.0_beta1/work/firefox'
 *   environment, line 2094:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";

**Comment by alcazoid** [comment]
Jesus, how to attach log here...

**Comment by pantera31752** [comment]
i will fix later

**Comment by pantera31752** [comment]
All right

**Comment by alcazoid** [comment]
For version www-client/firefox-39.0_beta2 it is 
Failed Patch: firefox-35.0-gmp-clearkey-sprintf.patch

**Comment by pantera31752** [comment]
I'm sorry, I will fix now
